GET http://localhost:8000/get_rules?drug=ozempic

###
POST http://localhost:8000/generate_plan
Content-Type: application/json

{
    "drug": "Ozempic",
    "rules": "Patient must be 18 years or older AND Patient must have a confirmed diagnosis of Type 2 diabetes AND Patient must have an A1C level of 7.0% or higher AND Patient must have a fasting plasma glucose (FPG) greater than or equal to 126 mg/dL OR Patient must have a 2-hour plasma glucose (PG) greater than or equal to 200 mg/dL during OGTT (oral glucose tolerance test) OR Patient must have a random plasma glucose greater than or equal to 200 mg/dL in patient with classic symptoms of hyperglycemia or hyperglycemic crisis."
}

###
POST http://localhost:8000/execute_plan
Content-Type: application/json

{
    "task":"Is the patient with patientId 1234 eligible for the Ozempic drug?",
    "plan": "Plan: Retrieve the patient's date of birth to determine if the patient is 18 years or older. #E1=get_patient_data[date_of_birth]\nPlan: Retrieve the patient's medical notes to confirm a diagnosis of Type 2 diabetes. #E2=get_patient_notes[diagnosis]\nPlan: Retrieve the patient's latest A1C test results to check if the A1C level is 7.0% or higher. #E3=get_patient_notes[A1C]\nPlan: Retrieve the patient's latest fasting plasma glucose (FPG) test results to check if it is greater than or equal to 126 mg/dL. #E4=get_patient_notes[FPG]\nPlan: Retrieve the patient's latest 2-hour plasma glucose (PG) test results during OGTT to check if it is greater than or equal to 200 mg/dL. #E5=get_patient_notes[2-hour PG during OGTT]\nPlan: Retrieve the patient's latest random plasma glucose test results to check if it is greater than or equal to 200 mg/dL in patient with classic symptoms of hyperglycemia or hyperglycemic crisis. #E6=get_patient_notes[random plasma glucose and symptoms]"
}
